### ISSUE TITLE
Uninitialized constant CustomRemindersEmailNotificationJob

### ISSUE THREAD

**Issue by ClemPaj** [woblavobla/redmine_custom_reminder#5]
Hi,

I tried to install the plugin following your Readme file. Everything went fine with the install. However, the plugin doesn't seem to work and I get the following message in the output error file `cron.stderr.log`: 

```
Please specify a valid ruby command or the path of a script to run.
Run 'bin/rails runner -h' for help.

uninitialized constant CustomRemindersEmailNotificationJob
```

I'm a complete noob in Ruby so I don't really know what to do here :)

Thanks in advance for you answer.

**Comment by ClemPaj** [comment]
Dear @woblavobla ,

I run Rails 5.2.2 and I did create redmine/app/jobs/application_job.rb. I don't know if it's of any help but I'm running Redmine inside a Docker container. 

Best regards
ClemPaj

**Comment by woblavobla** [comment]
Dear @ClemPaj ,

Docker container can face issues with running cron. Can you force schedule email notification in admin panel? If it works then we facing some problems when running scheduler by cron.

**Comment by colinlaney** [comment]
It's not exactly problem of `cron` within `docker`. It appears even manually.

### Phenomenology

I get the same error when I click force "Schedule email-notification" in  Administration panel of Redmine:
```
Completed 500 Internal Server Error in 64ms (ActiveRecord: 4.6ms)

NameError (uninitialized constant CustomRemindersController::CustomRemindersEmailNotificationJob
Did you mean?  CustomFieldEnumerationsController):

plugins/redmine_custom_reminder/app/controllers/custom_reminders_controller.rb:74:in `schedule_custom_reminder'
lib/redmine/sudo_mode.rb:63:in `sudo_mode'
``` 
---
Also when I execute
```
bundle exec bin/rails runner -e production 'CustomRemindersEmailNotificationJob.perform_now'
```
at `$REDMINE_ROOT` I'm just getting
```
Please specify a valid ruby command or the path of a script to run.
Run 'bin/rails runner -h' for help.

uninitialized constant CustomRemindersEmailNotificationJob
Did you mean?  CustomFieldEnumerationsController
```

### Environment

- Rails 5.2.2, Redmine 4.0.0
- I use [bitnami/redmine](https://hub.docker.com/r/bitnami/redmine) container with PostgreSQL
- Yes, I've created `($REDMINE_ROOT)/app/jobs/application_job.rb` as in instruction

**Comment by woblavobla** [comment]
@colinlaney you should perform migration. rake redmine:plugins
