### ISSUE TITLE
instalation problem

### ISSUE THREAD

**Issue by klakier666** [woblavobla/redmine_custom_reminder#7]
I have a problem with this plugin, i did all the install steps, i had some problems with some steps:

```
1) Clone repository to your plugins directory ($REDMINE_ROOT)/plugins
2) Create ruby file application_job.rb in ($REDMINE_ROOT)/app/jobs/application_job.rb with following content

    class ApplicationJob < ActiveJob::Base
      # Automatically retry jobs that encountered a deadlock
      # retry_on ActiveRecord::Deadlocked

      # Most jobs are safe to ignore if the underlying records are no longer available
      # discard_on ActiveJob::DeserializationError
    end

3) In your terminal execute bundle install at ($REDMINE_ROOT) to install needed gems
4) In your terminal execute rake redmine:plugins at ($REDMINE_ROOT) to perform database migration
5) In your terminal execute bundle exec whenever -i redmine_custom_reminder -f plugins/redmine_custom_reminder/config/schedule.rb at ($REDMINE_ROOT)
```
1. OK
2. OK
3. i think OK becouse i did not get any errors
4. rake redmine:plugins command had given me some errors
```
C:\Bitnami\redmine\apps\redmine\htdocs>rake redmine:plugins
rake aborted!
Mysql2::Error::ConnectionError: Access denied for user 'root'@'localhost' (using password: NO)
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/mysql2-0.5.2-x86-mingw32/lib/mysql2/client.rb:90:in `connect'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/mysql2-0.5.2-x86-mingw32/lib/mysql2/client.rb:90:in `initialize'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `new'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/mysql2_adapter.rb:22:in `mysql2_connection'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:811:in `new_connection'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:855:in `checkout_new_connection'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:834:in `try_to_checkout_new_connection'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:795:in `acquire_connection'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:523:in `checkout'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:382:in `connection'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1010:in `retrieve_connection'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:118:in `retrieve_connection'
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/activerecord-5.2.2/lib/active_record/connection_handling.rb:90:in `connection'
C:/Bitnami/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:538:in `get_all_versions'
C:/Bitnami/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:546:in `current_version'
C:/Bitnami/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:528:in `migrate_plugin'
C:/Bitnami/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:471:in `migrate'
C:/Bitnami/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:485:in `block in migrate'
C:/Bitnami/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:484:in `each'
C:/Bitnami/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:484:in `migrate'
C:/Bitnami/redmine/apps/redmine/htdocs/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
C:/Bitnami/redmine/apps/redmine/htdocs/lib/tasks/redmine.rake:57:in `block (2 levels) in <top (required)>'
Tasks: TOP => redmine:plugins:migrate
(See full trace by running task with --trace)
```
so i did:
```
rake redmine:plugins RAILS_ENV=production`
```
and i did not get any infolog just a new line without any message

5. and last i got an error while executing the last command

```
C:\Bitnami\redmine\apps\redmine\htdocs>bundle exec whenever -i redmine_custom_reminder -f plugins/redmine_custom_reminder/config/schedule.rb
The system cannot find the path specified.
C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:77:in `popen': No such file or directory - crontab - (Errno::ENOENT)
        from C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:77:in `write_crontab'
        from C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:38:in `run'
        from C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/whenever-0.10.0/lib/whenever/command_line.rb:6:in `execute'
        from C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/gems/whenever-0.10.0/bin/whenever:44:in `<top (required)>'
        from C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/bin/whenever:23:in `load'
        from C:/Bitnami/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.4.0/bin/whenever:23:in `<main>'
```

could someone with more knolage help me with this ?

```
Environment:
  Redmine version                4.0.1.stable
  Ruby version                   2.4.5-p335 (2018-10-18) [i386-mingw32]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.19.1
  Filesystem                     
Redmine plugins:
  redmine_activity_report        1.2.10
  redmine_banner                 0.2.0
  redmine_custom_reminder        0.6.3.db261d5
  redmine_issue_dynamic_edit     0.6.5
  redmine_lightbox2              0.5.0
  redmine_wysiwyg_editor         0.3.2
```

**Comment by woblavobla** [comment]
@klakier666 You should call every command in redmine's ROOT directory - and not in htdocs;

**Comment by klakier666** [comment]
this is my redmine root directory, im using bitnami stack 4.0.1

![obraz](https://user-images.githubusercontent.com/47813776/53729218-ede75500-3e74-11e9-92e6-e015676d0ba9.png)

**Comment by woblavobla** [comment]
@klakier666 your instance have no crontab.
