### ISSUE TITLE
I had an error when I activated the plugin

### ISSUE THREAD

**Issue by Lyaoer** [woblavobla/redmine_custom_reminder#8]
### some info:
I have finished the installation according to README.md
![image](https://user-images.githubusercontent.com/30254858/55316631-6c014080-54a1-11e9-8e77-656aecbd0889.png)
**Environment:**
  Redmine version                4.0.1.stable
  Ruby version                   2.5.3-p105 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.2

### When I visit the web page ,like this:
![image](https://user-images.githubusercontent.com/30254858/55316806-c00c2500-54a1-11e9-856b-99005b17f5e9.png)

### internal error message:
App 270 output: Error: The application encountered the following error: uninitialized constant ApplicationJob (NameError)
2019/4/1 pm5:17:46App 270 output:     /usr/src/redmine/plugins/redmine_custom_reminder/app/jobs/custom_reminders_email_notification_job.rb:1:in `<top (required)>'
2019/4/1 pm5:17:46App 270 output:     /usr/src/redmine/plugins/redmine_custom_reminder/app/controllers/custom_reminders_controller.rb:1:in `require_relative'
2019/4/1 pm5:17:46App 270 output:     /usr/src/redmine/plugins/redmine_custom_reminder/app/controllers/custom_reminders_controller.rb:1:in `<top (required)>'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/activesupport-5.2.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:477:in `each'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:477:in `block in eager_load!'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:475:in `each'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:475:in `eager_load!'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/engine.rb:356:in `eager_load!'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/application/finisher.rb:69:in `each'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `instance_exec'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:32:in `run'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:61:in `block in run_initializers'
2019/4/1 pm5:17:46App 270 output:     /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
2019/4/1 pm5:17:46App 270 output:     /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
2019/4/1 pm5:17:46App 270 output:     /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
2019/4/1 pm5:17:46App 270 output:     /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
2019/4/1 pm5:17:46App 270 output:     /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
2019/4/1 pm5:17:46App 270 output:     /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
2019/4/1 pm5:17:46App 270 output:     /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
2019/4/1 pm5:17:46App 270 output:     /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
2019/4/1 pm5:17:46App 270 output:     /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/initializable.rb:60:in `run_initializers'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/railties-5.2.2/lib/rails/application.rb:361:in `initialize!'
2019/4/1 pm5:17:46App 270 output:     /usr/src/redmine/config/environment.rb:14:in `<top (required)>'
2019/4/1 pm5:17:46App 270 output:     config.ru:3:in `require'
2019/4/1 pm5:17:46App 270 output:     config.ru:3:in `block in <main>'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
2019/4/1 pm5:17:46App 270 output:     config.ru:1:in `new'
2019/4/1 pm5:17:46App 270 output:     config.ru:1:in `<main>'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/passenger-6.0.1/src/helper-scripts/rack-preloader.rb:101:in `eval'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/passenger-6.0.1/src/helper-scripts/rack-preloader.rb:101:in `preload_app'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/passenger-6.0.1/src/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/passenger-6.0.1/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/passenger-6.0.1/src/helper-scripts/rack-preloader.rb:188:in `<module:App>'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/passenger-6.0.1/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
2019/4/1 pm5:17:46App 270 output:     /usr/local/bundle/gems/passenger-6.0.1/src/helper-scripts/rack-preloader.rb:29:in `<main>'
2019/4/1 pm5:17:46[ E 2019-04-01 17:17:45.7099 76/T16 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /usr/src/redmine: The application encountered the following error: uninitialized constant ApplicationJob (NameError)
2019/4/1 pm5:17:46  Error ID: 1201795c
2019/4/1 pm5:17:46  Error details saved to: /tmp/passenger-error-hj7ohr.html
2019/4/1 pm5:17:46
2019/4/1 pm5:17:46[ E 2019-04-01 17:17:45.7146 76/Te age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 4-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 1201795c. Please see earlier logs for details about the error.
2019/4/1 pm5:17:46[ E 2019-04-01 17:17:45.7149 76/Tg age/Cor/Con/CheckoutSession.cpp:276 ]: [Client 5-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 1201795c. Please see earlier logs for details about the error.

How can I solve this?

**Comment by Lyaoer** [comment]
I need to add a line `require_relative './application_job' `at custom_reminders_email_notification_job.rb
